/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
credits: https://sketchfab.com/3d-models/cartoon-aircraft-1701c134e4f3410e8a570def0e35b484
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import TransitionMaterial3 from './MeshTransitionMaterial/MeshTransitionMaterial3'
import { useFrame } from '@react-three/fiber'

export function Airplane({ transitionColor }, props) {
  const { nodes, materials } = useGLTF('/airplane.glb')
  const ref = useRef()

  useFrame((state) => {
    if (ref.current) {
      const elapsedTime = state.clock.getElapsedTime()
      ref.current.rotation.y = 5.9 * elapsedTime
    }
  })

  materials['Material.001'].thickness = 0.25
  materials['Material.001'].roughness = 0
  materials['Material.001'].metalness = 0
  materials['Material.001'].dispersion = 1.5
  materials['Material.001'].ior = 1.25
  materials['Material.001'].transmission = 1

  return (
    <group {...props} dispose={null}>
      <group position={[0.762, 0.11, -0.522]} rotation={[-1.591, 0.139, 0.127]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-1.695, -0.322, 0.287]}
            rotation={[-2.729, 0.061, 1.369]}
          >
            <mesh
              castShadow
              receiveShadow
              ref={ref}
              geometry={nodes.Object_14.geometry}
              material={materials.metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_15.geometry}
              material={materials.shadow}
            />
          </group>
          <group
            position={[-0.571, -0.188, 0.441]}
            rotation={[-1.574, -0.162, -1.707]}
            scale={[0.758, 1, 0.757]}
          >
            <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry}>
              <TransitionMaterial3
                roughness={0.2}
                // transmission={1}
                // dispersion={4.5}
                // thickness={1.25}
                transitionColor={transitionColor}
              />
            </mesh>
            <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry}>
              <TransitionMaterial3
                roughness={0.2}
                transitionColor={transitionColor}
              />
            </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials.shadow}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_65.geometry}
            material={materials.wire}
            position={[0.342, -0.342, 0.562]}
            rotation={[2.273, -1.36, 2.265]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_67.geometry}
            material={materials.wire}
            position={[0.315, -0.16, 0.775]}
            rotation={[2.273, -1.36, 2.265]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_69.geometry}
            material={materials.wire}
            position={[0.451, 0.476, 0.805]}
            rotation={[2.273, -1.36, 2.265]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_17.geometry}
            material={materials.metal}
            position={[0.498, 0.287, 0.594]}
            rotation={[0.019, -0.134, -1.408]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_19.geometry}
            material={materials['Material.002']}
            position={[-0.562, -0.703, 0.982]}
            rotation={[2.343, 0.21, -0.015]}
            scale={[0.12, 0.12, 0.11]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_21.geometry}
            position={[-0.562, -0.703, 0.982]}
            rotation={[2.343, 0.21, -0.015]}
            scale={[0.12, 0.12, 0.11]}
          >
            <TransitionMaterial3
              roughness={0.2}
              transitionColor={transitionColor}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_23.geometry}
            material={materials['Material.003']}
            position={[-1.389, -0.272, 0.329]}
            rotation={[1.567, 0.162, 1.707]}
            scale={0.27}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_25.geometry}
            material={materials['Material.003']}
            position={[-1.316, -0.26, 0.339]}
            rotation={[1.567, 0.162, 1.707]}
            scale={0.557}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_12.geometry}
            material={materials.metal}
            position={[-1.366, -0.285, 0.332]}
            rotation={[1.567, 0.162, 1.707]}
            scale={[0.645, 0.638, 0.645]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8.geometry}
            material={materials.metal}
            position={[-1.313, 0.397, 0.352]}
            rotation={[2.273, -1.36, 2.265]}
            scale={1.06}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_10.geometry}
            material={materials.metal}
            position={[-1.364, 0.379, 0.746]}
            rotation={[2.273, -1.36, 1.695]}
            scale={1.06}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_47.geometry}
            material={materials['Material.001']}
            position={[-0.571, -0.188, 0.441]}
            rotation={[-1.574, -0.162, -1.707]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_29.geometry}
            position={[0.222, 0.945, 0.569]}
            rotation={[1.567, 0.162, 0.136]}
          >
            <TransitionMaterial3
              roughness={0.2}
              transitionColor={transitionColor}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_31.geometry}
            material={materials['Material.002']}
            position={[0.178, 0.584, 0.557]}
            rotation={[1.567, 0.162, 0.136]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_27.geometry}
            material={materials.metal}
            position={[0.18, -0.341, 0.834]}
            rotation={[2.337, 0.675, -1.097]}
            scale={[0.115, 0.129, 0.088]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_33.geometry}
            material={materials.metal}
            position={[-0.572, -0.184, 0.441]}
            rotation={[2.822, -1.429, 2.806]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_37.geometry}
            material={materials['Material.002']}
            position={[0.239, -0.085, 0.889]}
            rotation={[0.482, -0.949, -1.443]}
            scale={0.033}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_39.geometry}
            material={materials['Material.002']}
            position={[0.322, -0.288, 0.66]}
            rotation={[0.51, -0.692, -1.802]}
            scale={0.035}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_41.geometry}
            material={materials['Material.002']}
            position={[0.38, -0.227, 0.626]}
            rotation={[0.507, -0.63, -1.812]}
            scale={0.035}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_43.geometry}
            material={materials['Material.002']}
            position={[0.348, 0.491, 0.725]}
            rotation={[0.41, -0.937, -0.356]}
            scale={0.033}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_45.geometry}
            material={materials['Material.002']}
            position={[0.414, -0.015, 0.76]}
            rotation={[0.466, -0.753, -1.591]}
            scale={0.033}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_35.geometry}
            material={materials['Material.002']}
            position={[0.176, -0.141, 0.917]}
            rotation={[0.488, -0.976, -1.442]}
            scale={0.035}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/airplane.glb')
